hwmon/applesmc: Exclude from build if CC_IS_CLANG && CC_OPTIMIZE_FOR_PERFORMANCE_O3
-O3 and beyond breaks driver build on Clang.

  ERROR: "__bad_udelay" [drivers/hwmon/applesmc.ko] undefined!
  make[1]: *** [scripts/Makefile.modpost:94: __modpost] Error 1
  make: *** [Makefile:1287: modules] Error 2

Signed-off-by: Albert I <kras@raphielgang.org>
Signed-off-by: Rapherion Rollerscaperers <rapherion@raphielgang.org>