arch: Kconfig: Disallow selecting JUMP_LABEL for Clang < 10.0.0
Avoid surprise build breakage due to incomplete asm goto support on Clang 9.

  In file included from ../drivers/infiniband/hw/cxgb4/cq.c:33:
  In file included from ../include/rdma/uverbs_ioctl.h:36:
  In file included from ../include/rdma/uverbs_types.h:36:
  In file included from ../include/linux/kernel.h:15:
  In file included from ../include/linux/printk.h:331:
  In file included from ../include/linux/dynamic_debug.h:6:
  In file included from ../include/linux/jump_label.h:117:
  ../arch/x86/include/asm/jump_label.h:25:20: error: invalid operand for inline asm constraint 'i'
          asm_volatile_goto("1:"
                          ^
  1 error generated.

Signed-off-by: Albert I <kras@raphielgang.org>
Signed-off-by: Rapherion Rollerscaperers <rapherion@raphielgang.org>